frameworkVersion: '3'
service: my-hideurl-project

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  environment:
    HIDE_TABLE: hideurl
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: !GetAtt HideUrlTable.Arn

package:
  exclude:
    - 'node_modules/**'
    - 'src/**'

functions:
  hideurl:
    handler: dist/bundle.handler
    name: hideurlfn
    events:
      - http:
          path: 'hideurl/{proxy+}'
          method: get
      - http:
          path: 'hideurl/{proxy+}'
          method: post
          authorizer:
            name: MyAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserpool
                - Arn
            scopes:
              - aws.cognito.signin.user.admin

resources:
  Resources:
    HideUrlTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: "hideurl"
    CognitoUserpool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: 'MyUserPool'
        AutoVerifiedAttributes:
          - email
    CognitoUserpoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        UserPoolId: !Ref CognitoUserpool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH